### ISSUE TITLE
Wrong wallet address created with Cosmostation App / tokens lost

### ISSUE THREAD

**Issue by activenodes** [cosmostation/cosmostation-ios#268] opened 2023-02-26 18:57 UTC
Dear Team,
I'm trying to use an old Akash wallet created with Cosmostation App (iPhone) in 2021.
The old saved **mnemonic (screenshot) and private key don't match with the wallet address** in the app.

Also:
- showing mnemonic
- exporting the private key
- checking the HD Key path (44/118/0 default)

from the current app and importing it in another Cosmostation App, a different address is created.
Note: both (mnemonic and private key) import the same address, but different from the original.

At last, trying to move tokens from the current wallet to another or staking... the application hang after the tx confirm, without any transaction on chain.

The current wallet has never executed tx, but only received tokens.

**Comment by wannabit-yongjoo** [comment] 2023-02-27 02:01
Dear @activenodes 
As you know, it is non-custodial, so we cannot be sure of your error.
But judging from the information you mentioned, it seems to be a problem with the early iPhone version of Cosmostation.

The problem was caused by the HD key problem of the Bitcoin library that we referenced earlier, with some corner case. 
And now the action has been completed.
But we made an engineer mode for users who generated keys in the past (like 2021).

Here's how you can check.
1 Activate engineer mode with setting (pw: ibcwallet)
2 Create an account from the mnemonic.
3 You will probably get a different address than the one created when engineer mode is turned off.
4 When engineer mode is on, the created address sends Tx only when engineer mode is on.
5 if you check your asset please transfer to new account.

If you have any questions or if it doesn't work, please ask for further inquiries.

**Comment by wannabit-yongjoo** [comment] 2023-02-27 02:01
![스크린샷 2023-02-27 오전 10 49 52](https://user-images.githubusercontent.com/38899600/221454841-75d29be1-768e-419d-a5a6-f5c05cb561c9.png)

**Comment by activenodes** [comment] 2023-02-27 09:55
Thank you @wannabit-yongjoo for the quick reply.

Here the result:

1 Another new/clean device (iOS) without the App
2 Intalled and activated the engineer mode (with password)
3 Imported account from the mnemonic
[Now the address is the same as in the old phone]
4 Create a "Send"
5 The TX hang on "Transaction Details" until timeout (as in the old/original device/wallet) without any any on-chain operation

Tokens are not transferred.

**Comment by wannabit-yongjoo** [comment] 2023-02-28 04:39
Dear @activenodes 

If the same address comes out regardless of engineer mode activation, it doesn't seem to be the corner case I mentioned earlier.

In particular, in the case of Akashi, I think it is strange because the default path of Cosmos is being used without any change.

To summarize the problem
You had one mnemonic,
Expected the address A to be derived,
But now deriving B Address, regardless of the engineer mode.
generate Tx with B is also not normally processed.
There was an asset at address A, but it is not accessible.

just in case
Please check your mnemonic again.
Can you confirm the address of the path m/44'/118'/0'/0/0 ~ m/44'/118'/0'/0/4?
Please test it in the Cosmos Extension wallet as well.

If this doesn't work, I'll check your address and public key.
It's loose, but it may contain your personal information, so it looks good to check it by e-mail.

support@cosmostation.io

**Comment by activenodes** [comment] 2023-02-28 08:39
Hello @wannabit-yongjoo, I try to summarize:

Original Phone:
- wallet created in 2021 and app updated during the years
- address akash1xxxxx
- details report HD: 44/118/0/0/0
- TX hang on "Transaction Details" until timeout

New Phone:
- app installed from scratch
- importing mnemonic
- the address is akash1zzzzz (different from the old phone)
- importing private key
- the address is akash1zzzzz (different from the old phone but the same as mnemonic)

New Phone with "eng-mode ON":
- app installed from scratch
- eng-mode activated
- importing mnemonic
- address akash1xxxxx (the same as original phone)
- details report HD: 44/118/0/0/0
- TX hang on "Transaction Details" until timeout (as the original phone)

Akash CLI:
- akash keys add WALLET --recover
- importing mnemonic
- the address is akash1zzzzz (different from the old phone, the same as new phone)

So "eng-mode" works, but TX doesn't work in any case.
Let me know if you want to check anything in the code for TX from old generations or eng-mode imported wallet.

Thank you again

**Comment by wannabit-yongjoo** [comment] 2023-02-28 08:57
OK got it

**Comment by wannabit-yongjoo** [comment] 2023-03-03 11:38
fixed with v1.8.4

**Closed by wannabit-yongjoo** 2023-03-03 11:38 UTC
